require("mini.ai").setup()
require("mini.pairs").setup()
require("mini.comment").setup()
require("mini.operators").setup()
-- require("mini.completion").setup()
require("mini.snippets").setup()
require("mini.icons").setup()
